/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import DTO.KhachThue;
import helper.ChuyenDoi;
import helper.ThongBao;
import java.util.ArrayList;
import helper.sqlHelper;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author quang nguyen
 */
public class jdlKhachThue extends javax.swing.JDialog {

    /**
     * Creates new form KhachThue2
     */
    public jdlKhachThue(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon("src/images/blue-home-icon.png");
        setIconImage(icon.getImage());
        ArrayList<KhachThue> arrKH = BLL.BLLKhachThue.GetAll();
        BLL.BLLKhachThue.DoVaoTable(arrKH, tblKhachThue);
//        jLabel90.setVisible(false);
//        rbNam.setVisible(false);
//        rbNu.setVisible(false);
    }

    public boolean validateform() {

        if (txtMaKH.getText().equals("") || txtTenKH.getText().equals("") || txtCMND.getText().equals("") || txtSDT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập ĐẦY ĐỦ THÔNG TIN!");
            return false;
        }

       

        return true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        panelKhachThue2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        JLHinhAnh = new javax.swing.JLabel();
        btnHInhAnhCD = new javax.swing.JButton();
        btnThemKH = new javax.swing.JButton();
        btnXoaKH = new javax.swing.JButton();
        btnSuaKH = new javax.swing.JButton();
        btnResetKH = new javax.swing.JButton();
        txtTimKiemKH = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        rbDangThue = new javax.swing.JRadioButton();
        rbDaTra = new javax.swing.JRadioButton();
        jLabel88 = new javax.swing.JLabel();
        JDNgaySinh = new com.toedter.calendar.JDateChooser();
        JDNgayVao = new com.toedter.calendar.JDateChooser();
        JLHinhCMNDTrc = new javax.swing.JLabel();
        btnHInhCMNDTrc = new javax.swing.JButton();
        JLHinhCMNDSau = new javax.swing.JLabel();
        btnHInhCMNDSau = new javax.swing.JButton();
        jLabel89 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblKhachThue = new javax.swing.JTable();
        jLabel90 = new javax.swing.JLabel();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        TBEmail = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelKhachThue2.setBackground(new java.awt.Color(0, 204, 255));

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));

        jPanel18.setBackground(new java.awt.Color(0, 204, 255));

        jLabel79.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel79.setText("Mã KH");

        jLabel80.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel80.setText("Tên KH");

        txtTenKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKHKeyReleased(evt);
            }
        });

        jLabel81.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel81.setText("Ngày sinh");

        jLabel82.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel82.setText("CCCD/CMND");

        txtCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCMNDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCMNDKeyTyped(evt);
            }
        });

        jLabel84.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel84.setText("SDT");

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSDTKeyTyped(evt);
            }
        });

        jLabel85.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel85.setText("Địa chỉ");

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        JLHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man-128px.png"))); // NOI18N

        btnHInhAnhCD.setBackground(new java.awt.Color(255, 255, 255));
        btnHInhAnhCD.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        btnHInhAnhCD.setText("Ảnh CD");
        btnHInhAnhCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHInhAnhCDActionPerformed(evt);
            }
        });

        btnThemKH.setBackground(new java.awt.Color(255, 255, 255));
        btnThemKH.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        btnThemKH.setText("Thêm KH");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        btnXoaKH.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaKH.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        btnXoaKH.setText("Xóa");
        btnXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKHActionPerformed(evt);
            }
        });

        btnSuaKH.setBackground(new java.awt.Color(255, 255, 255));
        btnSuaKH.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        btnSuaKH.setText("Sửa");
        btnSuaKH.setEnabled(false);
        btnSuaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKHActionPerformed(evt);
            }
        });

        btnResetKH.setBackground(new java.awt.Color(255, 255, 255));
        btnResetKH.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        btnResetKH.setText("Làm Mới");

        txtTimKiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemKHActionPerformed(evt);
            }
        });
        txtTimKiemKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKHKeyReleased(evt);
            }
        });

        jLabel86.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel86.setText("Ngày vào:");

        jLabel87.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel87.setText("Tình trạng");

        rbDangThue.setBackground(new java.awt.Color(0, 204, 255));
        buttonGroup2.add(rbDangThue);
        rbDangThue.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        rbDangThue.setText("Đang thuê");

        rbDaTra.setBackground(new java.awt.Color(0, 204, 255));
        buttonGroup2.add(rbDaTra);
        rbDaTra.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        rbDaTra.setText("Đã trả");
        rbDaTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDaTraActionPerformed(evt);
            }
        });

        jLabel88.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel88.setText("Tìm kiếm");

        JDNgaySinh.setDateFormatString("dd/MM/yyyy");

        JDNgayVao.setDateFormatString("dd/MM/yyyy");

        JLHinhCMNDTrc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLHinhCMNDTrc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man-128px.png"))); // NOI18N

        btnHInhCMNDTrc.setBackground(new java.awt.Color(255, 255, 255));
        btnHInhCMNDTrc.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        btnHInhCMNDTrc.setText("CMND trước");
        btnHInhCMNDTrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHInhCMNDTrcActionPerformed(evt);
            }
        });

        JLHinhCMNDSau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLHinhCMNDSau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man-128px.png"))); // NOI18N

        btnHInhCMNDSau.setBackground(new java.awt.Color(255, 255, 255));
        btnHInhCMNDSau.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        btnHInhCMNDSau.setText("CMND Sau");
        btnHInhCMNDSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHInhCMNDSauActionPerformed(evt);
            }
        });

        jLabel89.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel89.setText("Email");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        tblKhachThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH", "CCCD/CMND", "SDT", "Email", "Địa Chỉ", "Ngày Sinh", "Ngày Vào", "GTinh", "Tình trạng", "Ảnh CD", "Mặt trước", "Mặt sau"
            }
        ));
        tblKhachThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachThueMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblKhachThue);

        jLabel90.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        jLabel90.setText("Giới tính");

        rbNam.setBackground(new java.awt.Color(0, 204, 255));
        buttonGroup3.add(rbNam);
        rbNam.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        rbNam.setText("Nam");

        rbNu.setBackground(new java.awt.Color(0, 204, 255));
        buttonGroup3.add(rbNu);
        rbNu.setFont(new java.awt.Font("UTM Times", 1, 14)); // NOI18N
        rbNu.setText("Nữ");

        TBEmail.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel87))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(btnThemKH)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResetKH))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel18Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnHInhAnhCD, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHInhCMNDTrc)
                                    .addComponent(JLHinhCMNDTrc, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLHinhCMNDSau, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHInhCMNDSau, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(rbDangThue)
                                .addGap(34, 34, 34)
                                .addComponent(rbDaTra)))
                        .addGroup(jPanel18Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel90)
                            .addGap(27, 27, 27)
                            .addComponent(rbNam)
                            .addGap(34, 34, 34)
                            .addComponent(rbNu)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(txtTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel80)
                                        .addComponent(jLabel82))
                                    .addComponent(jLabel79, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel84, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel89, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel85, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel81, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel86, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TBEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(txtMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(txtTenKH)
                                    .addComponent(txtCMND)
                                    .addComponent(txtSDT)
                                    .addComponent(txtDiaChi)
                                    .addComponent(JDNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JDNgayVao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel79)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel89))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TBEmail)
                .addGap(4, 4, 4)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel81)
                    .addComponent(JDNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel86)
                    .addComponent(JDNgayVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90)
                    .addComponent(rbNam)
                    .addComponent(rbNu))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(rbDangThue)
                    .addComponent(rbDaTra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLHinhCMNDSau)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(JLHinhAnh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHInhAnhCD))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(JLHinhCMNDTrc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHInhCMNDTrc)
                            .addComponent(btnHInhCMNDSau))))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel88))
                    .addComponent(txtTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKH)
                    .addComponent(btnXoaKH)
                    .addComponent(btnSuaKH)
                    .addComponent(btnResetKH))
                .addContainerGap(171, Short.MAX_VALUE))
            .addComponent(jScrollPane8)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel29.setBackground(new java.awt.Color(0, 204, 255));
        jLabel29.setFont(new java.awt.Font("UTM Times", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("QUẢN LÝ KHÁCH THUÊ");
        jLabel29.setOpaque(true);

        javax.swing.GroupLayout panelKhachThue2Layout = new javax.swing.GroupLayout(panelKhachThue2);
        panelKhachThue2.setLayout(panelKhachThue2Layout);
        panelKhachThue2Layout.setHorizontalGroup(
            panelKhachThue2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKhachThue2Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 1228, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelKhachThue2Layout.setVerticalGroup(
            panelKhachThue2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKhachThue2Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1272, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(panelKhachThue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelKhachThue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void btnHInhAnhCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHInhAnhCDActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(btnHInhAnhCD);
        File file = chooser.getSelectedFile();
        String st = file.getPath();
        ImageIcon icon = new ImageIcon(new ImageIcon(file.getPath()).getImage().getScaledInstance(140, 200, Image.SCALE_SMOOTH));
        JLHinhAnh.setIcon(icon);
        System.out.println(st);
    }//GEN-LAST:event_btnHInhAnhCDActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        String MaNguoiThue;
        String TenNguoiThue;
        String CMND;
        String SDT;
        String DiaChi;
        String NgaySinh;
        String Email;
        String NgayTaoDT;
        boolean GioiTinh;
        boolean TrangThai;
        //            String NgayTra;
        if (validateform()) {
            MaNguoiThue = txtMaKH.getText();

            TenNguoiThue = txtTenKH.getText();
            DiaChi = txtDiaChi.getText();
            SDT = txtSDT.getText();
            Email = txtEmail.getText();
            if (rbNu.isSelected()) {
                GioiTinh = false;
            } else {
                GioiTinh = true;
            }
            if (rbDaTra.isSelected()) {
                TrangThai = true;
            } else {
                TrangThai = false;
            }
            CMND = txtCMND.getText();
            NgaySinh = ChuyenDoi.LayNgayString(JDNgaySinh.getDate());
            NgayTaoDT = ChuyenDoi.LayNgayString(JDNgayVao.getDate());

            KhachThue kh = new KhachThue(MaNguoiThue, TenNguoiThue, CMND, SDT, DiaChi, NgaySinh, NgayTaoDT, TrangThai);
            BLL.BLLKhachThue.Add(kh);
//            ThongBao.ThongBaoDonGian("Thông báo", "Đã thêm!");
            ArrayList<KhachThue> arr = BLL.BLLKhachThue.GetAll();

            BLL.BLLKhachThue.DoVaoTable(arr, tblKhachThue);
        }
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void btnXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKHActionPerformed
        int dongDangChon = tblKhachThue.getSelectedRow();
        if (dongDangChon < 0) {
            ThongBao.ThongBaoDonGian("Thông Báo", "Bạn chưa chọn khách hàng cần xóa");
        } else {
            int XacNhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc xóa không?", "Thông báo xác nhận", JOptionPane.OK_CANCEL_OPTION);
            if (XacNhan == JOptionPane.CANCEL_OPTION) {
                return;
            }
        }
        //Lấy danh sách các KH  cần xóa
        int dongCanXoa[] = tblKhachThue.getSelectedRows();

        for (int i = 0; i < dongCanXoa.length; i++) {
            String MaKhachHang = tblKhachThue.getValueAt(dongCanXoa[i], 0).toString();
            BLL.BLLKhachThue.Delete(MaKhachHang);
        }
        ArrayList<KhachThue> arr = BLL.BLLKhachThue.GetAll();
        BLL.BLLKhachThue.DoVaoTable(arr, tblKhachThue);
    }//GEN-LAST:event_btnXoaKHActionPerformed

    private void btnSuaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKHActionPerformed
        String MaNguoiThue;
        String TenNguoiThue;
        String CMND;
        String SDT;
        String DiaChi;
        String NgaySinh;
        String Email;
        String NgayTaoDT;
        boolean GioiTinh;
        boolean TrangThai;
        //            String NgayTra;
        if (validateform()) {
            MaNguoiThue = txtMaKH.getText();

            TenNguoiThue = txtTenKH.getText();
            DiaChi = txtDiaChi.getText();
            SDT = txtSDT.getText();
            Email = txtEmail.getText();
            if (rbNu.isSelected()) {
                GioiTinh = false;
            } else {
                GioiTinh = true;
            }
            if (rbDaTra.isSelected()) {
                TrangThai = true;
            } else {
                TrangThai = false;
            }
            CMND = txtCMND.getText();
            NgaySinh = ChuyenDoi.LayNgayString(JDNgaySinh.getDate());
            NgayTaoDT = ChuyenDoi.LayNgayString(JDNgayVao.getDate());

            int dongDangChon = tblKhachThue.getSelectedRow();
            if (dongDangChon < 0) {
                ThongBao.ThongBaoDonGian("Thông Báo", "Bạn chưa chọn khách hàng cần sửa");
            }
            String MaKhachHang = tblKhachThue.getValueAt(dongDangChon, 0).toString();
            KhachThue kh = new KhachThue(MaNguoiThue, TenNguoiThue, CMND, SDT, DiaChi, NgaySinh, NgayTaoDT, TrangThai);
            BLL.BLLKhachThue.Update(kh);

            ArrayList<KhachThue> arr = BLL.BLLKhachThue.GetAll();

            BLL.BLLKhachThue.DoVaoTable(arr, tblKhachThue);
        }
    }//GEN-LAST:event_btnSuaKHActionPerformed

    private void txtTimKiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemKHActionPerformed

    private void txtTimKiemKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKHKeyReleased
        // TODO add your handling code here:

        String tuKhoa = txtTimKiemKH.getText();
        ArrayList<KhachThue> arrSP = BLL.BLLKhachThue.FindByName(tuKhoa);
        BLL.BLLKhachThue.DoVaoTable(arrSP, tblKhachThue);
    }//GEN-LAST:event_txtTimKiemKHKeyReleased

    private void rbDaTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDaTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDaTraActionPerformed

    private void btnHInhCMNDTrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHInhCMNDTrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHInhCMNDTrcActionPerformed

    private void btnHInhCMNDSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHInhCMNDSauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHInhCMNDSauActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void tblKhachThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachThueMouseClicked
        int dongDangChon = tblKhachThue.getSelectedRow();
        if (dongDangChon < 0) {
            return;//Thoát
        }
        txtMaKH.setText(tblKhachThue.getValueAt(dongDangChon, 0).toString());
        txtTenKH.setText(tblKhachThue.getValueAt(dongDangChon, 1).toString());
        txtCMND.setText(tblKhachThue.getValueAt(dongDangChon, 2).toString());
        txtSDT.setText(tblKhachThue.getValueAt(dongDangChon, 3).toString());
        txtEmail.setText(tblKhachThue.getValueAt(dongDangChon, 4).toString());
        txtDiaChi.setText(tblKhachThue.getValueAt(dongDangChon, 5).toString());
        JDNgaySinh.setDate(ChuyenDoi.LayNgayDate(tblKhachThue.getValueAt(dongDangChon, 6).toString()));
        if (tblKhachThue.getValueAt(dongDangChon, 7) == null) {
            JDNgayVao.setDate(new Date());
        } else {
            JDNgayVao.setDate(ChuyenDoi.LayNgayDate(tblKhachThue.getValueAt(dongDangChon, 7).toString()));
        }
        if (tblKhachThue.getValueAt(dongDangChon, 8).toString() == "Nam") {
            rbNu.setSelected(false);
            rbNam.setSelected(true);
        } else {
            rbNu.setSelected(true);
            rbNam.setSelected(false);
        }
        if (tblKhachThue.getValueAt(dongDangChon, 9).toString() == "Đang Thuê") {
            rbDaTra.setSelected(false);
            rbDangThue.setSelected(true);
        } else {
            rbDaTra.setSelected(true);
            rbDangThue.setSelected(false);
        }

        btnSuaKH.setEnabled(true);
    }//GEN-LAST:event_tblKhachThueMouseClicked

    private void txtCMNDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMNDKeyTyped
    
      char a = evt.getKeyChar();
      if(!Character.isDigit(a)){
          evt.consume();
      }
    }//GEN-LAST:event_txtCMNDKeyTyped

    private void txtCMNDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMNDKeyReleased
       String CMND = txtCMND.getText();
       if(CMND.length() > 14){
           JOptionPane.showMessageDialog(null, "Số CMND tối đa 14 số ");
       }
    }//GEN-LAST:event_txtCMNDKeyReleased

    private void txtSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyReleased
       String SDT = txtSDT.getText();
       if(SDT.length() > 10){
           JOptionPane.showMessageDialog(null, "Số điện thoại tối đa 10 số ");
       }
    }//GEN-LAST:event_txtSDTKeyReleased

    private void txtSDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyTyped
      char a = evt.getKeyChar();
      if(!Character.isDigit(a)){
          evt.consume();
      }
    }//GEN-LAST:event_txtSDTKeyTyped

    private void txtTenKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKHKeyReleased
       String Name = txtTenKH.getText();
       if(!Name.matches("[a-zA-Z ,]+  ")){
           JOptionPane.showMessageDialog(null, "Tên phải là chữ");
       }
       
          
       
    }//GEN-LAST:event_txtTenKHKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        String Email = "^[a-zA-Z][a-zA-Z0-9]+@[a-zA-Z]+(\\.[a-zA-Z]+){1,3}$";
        Pattern email = Pattern.compile(Email);
        Matcher match =email.matcher(txtEmail.getText());
        if(!match.matches()){
            TBEmail.setText("Nhập chưa đúng định dạng Email!!");
        }else{
            TBEmail.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyReleased
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        ArrayList<KhachThue> arrKH = BLL.BLLKhachThue.GetAll();
        BLL.BLLKhachThue.DoVaoTable(arrKH, tblKhachThue);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlKhachThue dialog = new jdlKhachThue(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDNgaySinh;
    private com.toedter.calendar.JDateChooser JDNgayVao;
    private javax.swing.JLabel JLHinhAnh;
    private javax.swing.JLabel JLHinhCMNDSau;
    private javax.swing.JLabel JLHinhCMNDTrc;
    private javax.swing.JLabel TBEmail;
    private javax.swing.JButton btnHInhAnhCD;
    private javax.swing.JButton btnHInhCMNDSau;
    private javax.swing.JButton btnHInhCMNDTrc;
    private javax.swing.JButton btnResetKH;
    private javax.swing.JButton btnSuaKH;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel panelKhachThue2;
    private javax.swing.JRadioButton rbDaTra;
    private javax.swing.JRadioButton rbDangThue;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTable tblKhachThue;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKiemKH;
    // End of variables declaration//GEN-END:variables
}
