/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import DTO.*;
import helper.ThongBao;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class jdlThemDichVuPhong extends javax.swing.JDialog {

    /**
     * Creates new form jdlThemDichVuPhong
     */
    public jdlThemDichVuPhong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon("src/images/blue-home-icon.png");
        setIconImage(icon.getImage());
        ArrayList<DTO.PhongTro> list = BLL.BLLPhongTro.GetAll();
        txtMaPhong.setText(TrangChu.text);
        ArrayList<DichVu> arrDV = BLL.BLLDichVu.GetAll();
        BLL.BLLDichVu.DoVaoTable(arrDV, tbChiTietDichVu);
        for (PhongTro phongTro : list) {
            if (phongTro.getTenPhong().equals(FormChiTiet.TenPhong.getText())) {
                txtMaPhong.setText(phongTro.getMaPhong());
                txtTenPhong.setText(phongTro.getTenPhong());
            }
        }
        ArrayList<CTDV> arrCTDV = BLL.BLLChiTietDichVuPhong.FindByMaPhong(txtMaPhong.getText());
        BLL.BLLChiTietDichVuPhong.DoVaoTable(arrCTDV, tbDichVuPhong);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaPhong = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDichVuPhong = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbChiTietDichVu = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng ký dịch vụ phòng");

        txtMaPhong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtMaPhong.setText("txtMaPhong");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Mã phòng:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 22)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dịch vụ phòng");

        tbDichVuPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDichVuPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDichVuPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDichVuPhong);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Dịch vụ đã đăng ký");

        tbChiTietDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbChiTietDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChiTietDichVuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbChiTietDichVu);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Dịch vụ sẵn có");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Tên phòng:");

        txtTenPhong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTenPhong.setText("txtMaPhong");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(txtMaPhong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(txtTenPhong))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaPhong)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenPhong)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbChiTietDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChiTietDichVuMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            int dongChon = tbChiTietDichVu.getSelectedRow();
            int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thêm dịch vụ này?", "Thông báo xác nhận", JOptionPane.OK_CANCEL_OPTION);
            CTDV ct = new CTDV(txtMaPhong.getText(), tbChiTietDichVu.getValueAt(dongChon, 0).toString());
            if (xacNhan == JOptionPane.OK_OPTION) {
                if (BLL.BLLChiTietDichVuPhong.CheckHopLe(ct)) {
                    BLL.BLLChiTietDichVuPhong.Add(ct);
                } else {
                    ThongBao.ThongBaoDonGian("Thông báo", "Phòng đã đăng ký dịch vụ này!");
                }
            }
        }
        ArrayList<CTDV> arrCTDV = BLL.BLLChiTietDichVuPhong.FindByMaPhong(txtMaPhong.getText());
        BLL.BLLChiTietDichVuPhong.DoVaoTable(arrCTDV, tbDichVuPhong);
    }//GEN-LAST:event_tbChiTietDichVuMouseClicked

    private void tbDichVuPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDichVuPhongMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            int dongChon = tbDichVuPhong.getSelectedRow();
            int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn hủy dịch vụ này?", "Thông báo xác nhận", JOptionPane.OK_CANCEL_OPTION);
//            CTDV ct = new CTDV(txtMaPhong.getText(), tbChiTietDichVu.getValueAt(dongChon, 0).toString());
            if (xacNhan == JOptionPane.OK_OPTION) {
//                if (BLL.BLLChiTietDichVuPhong.CheckHopLe(ct)) {
                    BLL.BLLChiTietDichVuPhong.Delete(tbDichVuPhong.getValueAt(dongChon, 0).toString(), txtMaPhong.getText());
//                } else {
//                    ThongBao.ThongBaoDonGian("Thông báo", "Phòng đã đăng ký dịch vụ này!");
//                }
            }
        }
        ArrayList<CTDV> arrCTDV = BLL.BLLChiTietDichVuPhong.FindByMaPhong(txtMaPhong.getText());
        BLL.BLLChiTietDichVuPhong.DoVaoTable(arrCTDV, tbDichVuPhong);
    }//GEN-LAST:event_tbDichVuPhongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlThemDichVuPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlThemDichVuPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlThemDichVuPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlThemDichVuPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlThemDichVuPhong dialog = new jdlThemDichVuPhong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbChiTietDichVu;
    private javax.swing.JTable tbDichVuPhong;
    private javax.swing.JLabel txtMaPhong;
    private javax.swing.JLabel txtTenPhong;
    // End of variables declaration//GEN-END:variables
}
